
development: 
  adapter: postgresql
  host: ec2-54-204-7-145.compute-1.amazonaws.com
  username: fggzzmfjddfdog
  password: kmKpJBgZDY9snaa0XRbruGRL54
  database: d6b92gpg9pf0n7

test: &test
  adapter: postgresql
  host: ec2-54-204-7-145.compute-1.amazonaws.com
  username: fggzzmfjddfdog
  password: kmKpJBgZDY9snaa0XRbruGRL54
  database: d855ml6rvj5pj2
cucumber:
  <<: *test